import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Navbar, Footer } from "@/utils/NavFoot";
import "../styles/globals.css";

const inter = Inter({ subsets: ['latin'] })



export const metadata = {
  title: "ZephyrAssets",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="topography-bg min-h-screen min-w-sreen cursor-default">
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}

