import { DAppProvider, useEthers } from '@usedapp/core';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className="topography-bg min-h-screen min-w-sreen cursor-default">
          {children}
        </body>
    </html>
  )
}
